//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Assignment_2_CSI2441Entities1 : DbContext
    {
        public Assignment_2_CSI2441Entities1()
            : base("name=Assignment_2_CSI2441Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Unit_Enrolment> Unit_Enrolment { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        //public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
