//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Unit_Enrolment = new HashSet<Unit_Enrolment>();
        }

        [Display(Name = "Student ID")]
        [Required(ErrorMessage = "Student ID cannot be empty!")]
        [RegularExpression(@"^[0-9]{8}$", ErrorMessage = "Student ID must contain 8 digits!")]
        public string StudentID { get; set; }

        [Display(Name = "Student Name")]
        [Required(ErrorMessage = "Student Name cannot be empty!")]
        public string StudentName { get; set; }

        [Display(Name = "Student Photo")]
        public string StudentPhoto { get; set; }

        public HttpPostedFileBase PhotoFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit_Enrolment> Unit_Enrolment { get; set; }

    }
}
