//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.Unit_Enrolment = new HashSet<Unit_Enrolment>();
        }

        [Display(Name = "Unit Code")]
        [Required(ErrorMessage = "Unitcode cannot be empty!")]
        [RegularExpression(@"^[A-Za-z]{3}\d{4}$", ErrorMessage = "Unitcode doesn't match the required format! (Format: AAA-1111)")]
        public string UnitCode { get; set; }

        [Display(Name = "Unit Title")]
        [Required(ErrorMessage = "Unit Title cannot be empty!")]
        public string UnitTitle { get; set; }

        [Display(Name = "Unit Coordinator")]
        public string UnitCoordinator { get; set; }

        [Display(Name = "Unit Outline")]
        public string UnitOuttlinePdf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit_Enrolment> Unit_Enrolment { get; set; }
    }
}
